rtorrent:
    image: "neoden/alpine-rtorrent:latest"
    volumes:
        - "$HOME/Downloads/torrents/download:/data/download/"
        - "$HOME/Downloads/torrents/completed:/data/completed/"
        - "$HOME/Downloads/torrents/watch:/data/watch/"
        - "$HOME/Downloads/torrents/session:/data/session/"
    expose:
        - "6881"
        - "49264"
        - "3000"
    tty: true
